#!/bin/bash

# Simple for loop
for var in 1 2 "I'm string" false 5
do  
    echo This is $var
done

# Using comands as source of array
echo "--------------------------------"
echo "Contents of this folder are:"
for var in $(ls .)
do  
    echo $var
done

# Using custom field separator separator. Default separators: space, tab, newline
echo "--------------------------------"
echo "Users of this OS:"
file="/etc/passwd"
IFS=$'\n'
for var in $(cat $file)
do  
    echo $var
done

# Iterating over files in directory
echo "--------------------------------"
echo "Direcotory $HOME contains:"
for file in $HOME/*
do
    if [ -d $file ] 
        then echo "$file is directory."
    elif [ -f $file ]
        then echo "$file is file"
    fi
done 