#!/bin/bash

# Simple for loop
for var in 1 2 "I'm string" false 5
do  
    echo This is $var
done

# Using comands as source of array
echo "--------------------------------"
echo "Contents of this folder are:"
for var in $(ls .)
do  
    echo $var
done

# Using custom field separator separator. Default separators: space, tab, newline
echo "--------------------------------"
echo "Users of this OS:"
file="/etc/passwd"
IFS=$'\n'
for var in $(cat $file)
do  
    echo $var
done

# Iterating over files in directory
echo "--------------------------------"
echo "Direcotory $HOME contains:"
for file in $HOME/*
do
    if [ -d $file ] 
        then echo "$file is directory."
    elif [ -f $file ]
        then echo "$file is file"
    fi
done 

# C style for loop
echo "--------------------------------"
for (( i=1; i<=10; i++ ))
do
    echo "Current number is $i"
done

# While loop
echo "--------------------------------"
var1=10
while [ $var1 -gt 0 ]
do
    echo "Current number is $var1"
    var1=$[ $var1 - 1 ]
done

# Nested loops
echo "--------------------------------"
for (( i=1; i<=3; i++ ))
do
    echo "Outer $i"
    for (( j=1; j<=3; j++ ))
    do
        echo "Outer $i Inner $j"
    done
done

# Continue and break
echo "--------------------------------"
for (( i=1; i<=3; i++ ))
do
    echo "Outer $i"
    for (( j=1; j<=3; j++ ))
    do
        if [ $j -eq 2 ]
            then continue
        fi
        echo "Outer $i Inner $j"
    done

    if [ $i -eq 2 ]
        then break
    fi
done

# Piping result
echo "--------------------------------"
logFile="nested.log"
for (( i=1; i<=3; i++ ))
do
    echo "Outer $i"
    for (( j=1; j<=3; j++ ))
    do
        echo "Outer $i Inner $j"
    done
done > $logFile

# Example: listing executable files
echo "--------------------------------"
executableListFile="executableFiles.txt"
IFS=:
for folder in $PATH
do
    echo "$folder contains:"
    for file in $folder/*
    do
        if [ -x $file ]
            then echo " $file"
        fi
    done
done > $executableListFile