#!/bin/bash

# Separating options from parameters
while [ -n "$1" ]
do
    case "$1" in
        -a) echo "Found the -a option";;
        -b) echo "Found the -b option";;
        -c) echo "Found the -c option";;
        # Usually -- used to mark end of options and start of parameters
        --) shift; break;
    esac
    shift
done
count=1
echo "params $@"
for param in "$@"
do
    echo "Parameter #$count: $param"
    count=$(( $count + 1 ))
done
